#!/usr/bin/env python3
"""
Adds the albums that are in the personal collection sheet but never made it
into the database -- records bought after the original Discogs import.

Confirmed missing by two passes: matched on Discogs release id, then again
on title alone (which caught "Celia Cruz, Willie Colón" and "Fela Kuti,
Africa 70" already being present under different pressings -- those are
deliberately NOT in the list below).

No Discogs token needed: this goes through the site's own /api/discogs
endpoint, which holds the token server-side. That also means it works from
anywhere, and there's no token to leak into this file.

    python3 build_missing_albums_sql.py

Writes import_missing.sql -- paste into the Supabase SQL Editor and run.
"""
import json, urllib.request, uuid, sys, time

SITE = "https://darguelles-viniles.vercel.app"

# (release_id, genre, notes) -- genre and notes come from the sheet, which
# is the source of truth for both. Everything else comes from Discogs.
WANTED = [
    (33646428, "Electronic",        "Record Store Day 2025; London"),
    (6510365,  "R&B/Soul",          "Record Store Day 2025; London"),
    (35786479, "Folk",              ""),
    (28862140, "Folk",              ""),
    (33265488, "Electronic",        ""),
    (36615520, "Alternative/Indie", "Added from Discogs"),
    (19995013, "Afrobeat",          ""),
    (25341883, "Electronic",        ""),
    (22972040, "Electronic",        ""),
    (24961471, "Electronic",        ""),
    (33675372, "Alternative/Indie", "Record Store Day 2025; London"),
    (31442732, "Blues",             ""),
    (1159835,  "Jazz",              ""),
    (37109694, "Folk",              "Added from Discogs"),
    (25246954, "Electronic",        "Added from Discogs"),
    (7383499,  "Jazz",              "Regalo Ysita: Intercambio V&G"),
    (14145883, "Folk",              "Added from Discogs"),
    (33673704, "R&B/Soul",          "Record Store Day 2025; London"),
    (22720388, "Jazz",              ""),
    (3555769,  "Rock",              ""),
    (32416620, "R&B/Soul",          "Added from Discogs"),
    (28021260, "Rock",              "Added from Discogs"),
    (23350427, "Alternative/Indie", ""),
    (31852928, "Alternative/Indie", ""),
    (33697767, "Jazz",              "Record Store Day 2025; London"),
    (19943617, "Salsa/Tropical",    ""),
]


def esc(s):
    if s is None or s == "":
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def esc_arr(items):
    if not items:
        return "'{}'"
    inner = ",".join('"' + str(x).replace('"', '\\"').replace("'", "''") + '"' for x in items)
    return "'{" + inner + "}'"


def fetch(release_id):
    url = f"{SITE}/api/discogs?mode=release&id={release_id}"
    with urllib.request.urlopen(url, timeout=30) as r:
        return json.load(r)


def main():
    lines = [
        "-- Albums present in the personal sheet but missing from the database.",
        "-- Generated by build_missing_albums_sql.py. Paste and run once.",
        "",
        "begin;",
        "",
    ]

    ok, failed = 0, []
    for rid, genre, notes in WANTED:
        try:
            rel = fetch(rid)
        except Exception as e:
            failed.append((rid, str(e)))
            print(f"  !! {rid} failed: {e}")
            continue

        new_id = str(uuid.uuid4())
        # Must match records_format_check -- see
        # ../migrations/006_allow_multi_disc_formats.sql, which has to be
        # run before this import.
        fmt = rel.get("format") or "LP"
        if fmt not in ("LP", "2xLP", "3xLP", "EP", "Single", '12"', "Box Set"):
            fmt = "LP"

        lines.append(
            "insert into records (id, artist, title, original_year, pressing_year, label, "
            "catalog_no, discogs_release_id, format, genres, cover_url, my_notes, owner) values ("
            f"{esc(new_id)}, {esc(rel.get('artist'))}, {esc(rel.get('title'))}, "
            f"{rel.get('original_year') or 'NULL'}, {rel.get('pressing_year') or 'NULL'}, "
            f"{esc(rel.get('label'))}, {esc(rel.get('catalog_no'))}, {rid}, "
            f"{esc(fmt)}, {esc_arr([genre])}, {esc(rel.get('cover_url'))}, {esc(notes)}, 'Diego');"
        )
        for t in rel.get("tracks", []):
            if not t.get("title"):
                continue
            lines.append(
                "insert into tracks (record_id, position, title, duration) values ("
                f"{esc(new_id)}, {esc(t.get('position'))}, {esc(t.get('title'))}, {esc(t.get('duration'))});"
            )

        ok += 1
        print(f"  ok {rel.get('artist')} - {rel.get('title')}")
        time.sleep(1)  # be polite to the Discogs rate limit

    lines += [
        "",
        "commit;",
        "",
        "-- Should now report 141 records for Diego.",
        "select count(*) from records where owner = 'Diego';",
        "",
    ]

    with open("import_missing.sql", "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\nWrote import_missing.sql: {ok} albums")
    if failed:
        print(f"{len(failed)} failed -- tell Claude which:")
        for rid, err in failed:
            print(f"  {rid}: {err}")


if __name__ == "__main__":
    main()
