-- Genre cleanup: restore Diego's own genres from the personal
-- collection sheet, overwriting what the Discogs import guessed.
-- Joined on discogs_release_id, scoped to owner = 'Diego'.
-- Safe to re-run: it just sets the same values again.

begin;

update records set genres = ARRAY['Electronic'] where discogs_release_id = 29792263 and owner = 'Diego';
update records set genres = ARRAY['Pop'] where discogs_release_id = 3050226 and owner = 'Diego';
update records set genres = ARRAY['Blues'] where discogs_release_id = 2835842 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 4041377 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 8236333 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 36610048 and owner = 'Diego';
update records set genres = ARRAY['Blues'] where discogs_release_id = 7579375 and owner = 'Diego';
update records set genres = ARRAY['Reggae'] where discogs_release_id = 6657017 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 9150523 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 2940876 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 15857861 and owner = 'Diego';
update records set genres = ARRAY['Salsa/Tropical'] where discogs_release_id = 20165404 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 23575493 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 24455669 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 32586471 and owner = 'Diego';
update records set genres = ARRAY['Soundtrack'] where discogs_release_id = 9299215 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 8950450 and owner = 'Diego';
update records set genres = ARRAY['Salsa/Tropical'] where discogs_release_id = 8655907 and owner = 'Diego';
update records set genres = ARRAY['Hip Hop'] where discogs_release_id = 14752006 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 19277239 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 12186161 and owner = 'Diego';
update records set genres = ARRAY['Blues'] where discogs_release_id = 9190560 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 3979641 and owner = 'Diego';
update records set genres = ARRAY['Hip Hop'] where discogs_release_id = 23398166 and owner = 'Diego';
update records set genres = ARRAY['Hip Hop'] where discogs_release_id = 24295229 and owner = 'Diego';
update records set genres = ARRAY['Hip Hop'] where discogs_release_id = 3975953 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 10776167 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 2395827 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 5731386 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 14339446 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 5743279 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 762954 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 5077187 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 6266472 and owner = 'Diego';
update records set genres = ARRAY['Pop'] where discogs_release_id = 33488300 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 2825456 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 24629744 and owner = 'Diego';
update records set genres = ARRAY['Blues'] where discogs_release_id = 10962185 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 20771251 and owner = 'Diego';
update records set genres = ARRAY['Funk'] where discogs_release_id = 70285 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 1049858 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 12214436 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 35505388 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 13468772 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 23429402 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 10095109 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 30669100 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 8851020 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 10270350 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 34746321 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 9814889 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 24027815 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 11147862 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 10892412 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 323708 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 29396857 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 7091295 and owner = 'Diego';
update records set genres = ARRAY['Hip Hop'] where discogs_release_id = 14195392 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 16213475 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 4881115 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 9981969 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 11721142 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 29446156 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 6238189 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 25419349 and owner = 'Diego';
update records set genres = ARRAY['Folk'] where discogs_release_id = 7764708 and owner = 'Diego';
update records set genres = ARRAY['Pop'] where discogs_release_id = 9404930 and owner = 'Diego';
update records set genres = ARRAY['Classical'] where discogs_release_id = 9674692 and owner = 'Diego';
update records set genres = ARRAY['Blues'] where discogs_release_id = 6334650 and owner = 'Diego';
update records set genres = ARRAY['Blues'] where discogs_release_id = 4793522 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 10488255 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 8541806 and owner = 'Diego';
update records set genres = ARRAY['Blues'] where discogs_release_id = 25174057 and owner = 'Diego';
update records set genres = ARRAY['Folk'] where discogs_release_id = 25050289 and owner = 'Diego';
update records set genres = ARRAY['Funk'] where discogs_release_id = 29200381 and owner = 'Diego';
update records set genres = ARRAY['Classical'] where discogs_release_id = 16169179 and owner = 'Diego';
update records set genres = ARRAY['Hip Hop'] where discogs_release_id = 10559651 and owner = 'Diego';
update records set genres = ARRAY['Hip Hop'] where discogs_release_id = 24882914 and owner = 'Diego';
update records set genres = ARRAY['Classical'] where discogs_release_id = 15683147 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 28989175 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 2383925 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 15469494 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 1312950 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 29578063 and owner = 'Diego';
update records set genres = ARRAY['Folk'] where discogs_release_id = 24747581 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 26226236 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 17535775 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 14401718 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 6292831 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 20857672 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 22926317 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 29817418 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 4666796 and owner = 'Diego';
update records set genres = ARRAY['Reggae'] where discogs_release_id = 7240889 and owner = 'Diego';
update records set genres = ARRAY['Pop'] where discogs_release_id = 28034796 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 3337799 and owner = 'Diego';
update records set genres = ARRAY['Folk'] where discogs_release_id = 12258791 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 4453244 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 3738094 and owner = 'Diego';
update records set genres = ARRAY['Reggae'] where discogs_release_id = 5011619 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 25062901 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 32121774 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 4970787 and owner = 'Diego';
update records set genres = ARRAY['Reggae'] where discogs_release_id = 20362099 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 3668613 and owner = 'Diego';
update records set genres = ARRAY['Classical'] where discogs_release_id = 17841076 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 14297380 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 2979143 and owner = 'Diego';
update records set genres = ARRAY['Reggae'] where discogs_release_id = 16544148 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 3555769 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 33265488 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 33675372 and owner = 'Diego';
update records set genres = ARRAY['Salsa/Tropical'] where discogs_release_id = 33676011 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 33646428 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 33673704 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 33697767 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 6510365 and owner = 'Diego';
update records set genres = ARRAY['Blues'] where discogs_release_id = 9025167 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 25341883 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 22972040 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 24961471 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 23350427 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 7383499 and owner = 'Diego';
update records set genres = ARRAY['Blues'] where discogs_release_id = 31442732 and owner = 'Diego';
update records set genres = ARRAY['Folk'] where discogs_release_id = 35786479 and owner = 'Diego';
update records set genres = ARRAY['Folk'] where discogs_release_id = 28862140 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 31852928 and owner = 'Diego';
update records set genres = ARRAY['Salsa/Tropical'] where discogs_release_id = 19943617 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 22720388 and owner = 'Diego';
update records set genres = ARRAY['Jazz'] where discogs_release_id = 1159835 and owner = 'Diego';
update records set genres = ARRAY['Afrobeat'] where discogs_release_id = 19995013 and owner = 'Diego';
update records set genres = ARRAY['Afrobeat'] where discogs_release_id = 6206132 and owner = 'Diego';
update records set genres = ARRAY['Folk'] where discogs_release_id = 37109694 and owner = 'Diego';
update records set genres = ARRAY['Alternative/Indie'] where discogs_release_id = 36615520 and owner = 'Diego';
update records set genres = ARRAY['Electronic'] where discogs_release_id = 25246954 and owner = 'Diego';
update records set genres = ARRAY['R&B/Soul'] where discogs_release_id = 32416620 and owner = 'Diego';
update records set genres = ARRAY['Rock'] where discogs_release_id = 28021260 and owner = 'Diego';
update records set genres = ARRAY['Folk'] where discogs_release_id = 14145883 and owner = 'Diego';

-- One sheet row has no Discogs release id, so it matches on name.
update records set genres = ARRAY['Alternative/Indie'] where artist = 'Monairem' and title = 'Moonscape' and owner = 'Diego';

commit;

-- Check afterwards: how the collection now breaks down by genre.
select genres[1] as genre, count(*) from records where owner = 'Diego' group by genres[1] order by count(*) desc;

